name: Deploy doc folder to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Subir carpeta `doc/` al servidor
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: a23elivalyen.daw.inspedralbes.cat
        REMOTE_USER: a23elivalyen
        REMOTE_PORT: 22
        SOURCE: doc/
        TARGET: a23elivalyen.daw.inspedralbes.cat/public_html/actions
