name: Deploy Vue app to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm ci

      - name: Construir el proyecto Vue
        run: npm run build

      - name: Subir carpeta dist/ al servidor
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: a23elivalyen.daw.inspedralbes.cat
          REMOTE_USER: a23elivalyen
          REMOTE_PORT: 22
          SOURCE: dist/
          TARGET: /home/a23elivalyen/web/a23elivalyen.daw.inspedralbes.cat/public_html/vue
          ARGS: --delete
